const SY2223 = {
  schoolyear: "SY2223",
  terms: [
    {
      termCode: "t1_SY2223",
      termName: "T1",
      beg: new Date("Aug 08, 2022"),
      end: new Date("Oct 07, 2022"),
    },
    {
      termCode: "t2_SY2223",
      termName: "T2",
      beg: new Date("Oct 09, 2022"),
      end: new Date("Dec 16, 2022"),
    },
    {
      termCode: "t3_SY2223",
      termName: "T3",
      beg: new Date("Jan 04, 2023"),
      end: new Date("Mar 03, 2023"),
    },
    {
      termCode: "t4_SY2223",
      termName: "T4",
      beg: new Date("Mar 06, 2023"),
      end: new Date("May 12, 2023"),
    },
    {
      termCode: "ps_SY2223",
      termName: "Postsession",
      beg: new Date("May 15, 2023"),
      end: new Date("May 26, 2023"),
    },
    {
      termCode: "ss_SY2223",
      termName: "Summer School",
      beg: new Date("May 30, 2023"),
      end: new Date("Jun 30, 2023"),
    },
  ],
  dates: [
    {
      beg: new Date("Sep 05, 2022"),
      end: new Date("Sep 05, 2022"),
      eventType: "studentHoliday",
      name: "Labor Day",
      description: "",
    },
    {
      beg: new Date("Jul 04, 2022"),
      end: new Date("Jul 04, 2022"),
      eventType: "studentHoliday",
      name: "Independence Day",
      description: "",
    },
    {
      beg: new Date("Aug 03, 2022"),
      end: new Date("Aug 03, 2022"),
      eventType: "studentHoliday",
      name: "PD Day",
      description: "",
    },
    {
      beg: new Date("Aug 04, 2022"),
      end: new Date("Aug 04, 2022"),
      eventType: "studentHoliday",
      name: "Collaboration / Work Day",
      description: "",
    },
    {
      beg: new Date("Aug 05, 2022"),
      end: new Date("Aug 05, 2022"),
      eventType: "studentHoliday",
      name: "Teacher Work Day",
      description: "",
    },
    {
      beg: new Date("Aug 07, 2022"),
      end: new Date("Aug 07, 2022"),
      eventType: "event",
      name: "First Day of School",
      description: "",
    },
    {
      beg: new Date("Sep 16, 2022"),
      end: new Date("Sep 16, 2022"),
      eventType: "studentHoliday",
      name: "PD Day",
      description: "",
    },
    {
      beg: new Date("Oct 10, 2022"),
      end: new Date("Oct 10, 2022"),
      eventType: "studentHoliday",
      name: "Indigenous Peoples' Day",
      description: "",
    },
    {
      beg: new Date("Nov 11, 2022"),
      end: new Date("Nov 11, 2022"),
      eventType: "studentHoliday",
      name: "Veterans' Day",
      description: "",
    },
    {
      beg: new Date("Nov 21, 2022"),
      end: new Date("Nov 25, 2022"),
      eventType: "studentHoliday",
      name: "Thanksgiving Break",
      description: "",
    },
    {
      beg: new Date("Dec 19, 2022"),
      end: new Date("Dec 30, 2022"),
      eventType: "studentHoliday",
      name: "Winter Break",
      description: "",
    },
    {
      beg: new Date("Jan 02, 2023"),
      end: new Date("Jan 02, 2023"),
      eventType: "studentHoliday",
      name: "New Year's Day",
      description: "",
    },
    {
      beg: new Date("Jan 03, 2023"),
      end: new Date("Jan 03, 2023"),
      eventType: "studentHoliday",
      name: "PD Day",
      description: "",
    },
    {
      beg: new Date("Jan 04, 2023"),
      end: new Date("Jan 04, 2023"),
      eventType: "event",
      name: "First Day of Spring Semester",
      description: "",
    },
    {
      beg: new Date("Jan 16, 2023"),
      end: new Date("Jan 16, 2023"),
      eventType: "studentHoliday",
      name: "Martin Luther King, Jr. Day",
      description: "",
    },
    {
      beg: new Date("Feb 20, 2023"),
      end: new Date("Feb 20, 2023"),
      eventType: "studentHoliday",
      name: "Presidents' Day",
      description: "",
    },
    {
      beg: new Date("Mar 31, 2023"),
      end: new Date("Mar 31, 2023"),
      eventType: "studentHoliday",
      name: "Cesar Chavez Day",
      description: "",
    },
    {
      beg: new Date("Apr 03, 2023"),
      end: new Date("Apr 07, 2023"),
      eventType: "studentHoliday",
      name: "Spring Break",
      description: "",
    },
    {
      beg: new Date("May 25, 2023"),
      end: new Date("May 25, 2023"),
      eventType: "event",
      name: "Last Day of Instruction",
      description: "",
    },
    {
      beg: new Date("May 26, 2023"),
      end: new Date("May 26, 2023"),
      eventType: "studentHoliday",
      name: "Teacher Work Day",
      description: "",
    },
    {
      beg: new Date("May 29, 2023"),
      end: new Date("May 29, 2023"),
      eventType: "studentHoliday",
      name: "Memorial Day",
      description: "",
    },
    {
      beg: new Date("Jun 19, 2023"),
      end: new Date("Jun 19, 2023"),
      eventType: "studentHoliday",
      name: "Juneteenth Holiday",
      description: "",
    },
    {
      beg: new Date("Jul 10, 2022"),
      end: new Date("Jul 10, 2022"),
      eventType: "event",
      name: "Eid al-Adha",
      description:
        "Muslim holiday, begins the prior evening, some observe the holiday for up to four days",
    },
    {
      beg: new Date("Sep 26, 2022"),
      end: new Date("Sep 26, 2022"),
      eventType: "event",
      name: "Rosh Hashanah",
      description:
        "Jewish holiday, begins the prior evening, some observe the holiday for a second day",
    },
    {
      beg: new Date("Oct 05, 2022"),
      end: new Date("Oct 05, 2022"),
      eventType: "event",
      name: "Yom Kippur",
      description: "Jewish holiday, begins the prior evening",
    },
    {
      beg: new Date("Oct 24, 2022"),
      end: new Date("Oct 24, 2022"),
      eventType: "event",
      name: "Diwali",
      description:
        "Hindi holiday, some observe the holiday for up to four days; other religions also celebrate Diwali, but not necessarily on the same day",
    },
    {
      beg: new Date("Dec 08, 2022"),
      end: new Date("Dec 08, 2022"),
      eventType: "event",
      name: "Bodhi",
      description: "Buddhist holiday, some observe the holiday in January",
    },
    {
      beg: new Date("Dec 25, 2022"),
      end: new Date("Dec 25, 2022"),
      eventType: "event",
      name: "Christmas",
      description: "Christian holiday",
    },
    {
      beg: new Date("Jan 15, 2023"),
      end: new Date("Jan 15, 2023"),
      eventType: "event",
      name: "Makar Sankranti / Pongal / Tirmoori",
      description:
        "Hindi holiday, some observe the holiday for up to four days",
    },
    {
      beg: new Date("Apr 09, 2023"),
      end: new Date("Apr 09, 2023"),
      eventType: "event",
      name: "Easter",
      description: "Christian holiday",
    },
    {
      beg: new Date("Apr 22, 2023"),
      end: new Date("Apr 22, 2023"),
      eventType: "event",
      name: "Eid al-Fitr",
      description:
        "Muslim holiday, begins the prior evening, +/- day dependent on the sighting of the crescent moon",
    },
    {
      beg: new Date("May 05, 2023"),
      end: new Date("May 05, 2023"),
      eventType: "event",
      name: "Vesak",
      description:
        "Buddhist holiday, some observe the holiday in April or on other days in May",
    },
  ],
};
